### PR TITLE
Add option to build from uncommitted changes.

### LINKED ISSUE #3: unable to build from uncommitted changes
Is there a specific reason why building from uncommitted files is not possible?

Imo it is very counter-intuitive to be forced to commit my untested changes to make testing even possible.

### PR DESCRIPTION
**Pull request by zjosua**
#### Description

Fixes #3.

#### Checklist:

*Please replace the space inside the brackets with an **x** and fill out the ellipses if the following items apply:*

- [x] I've read and understood the ~~[contribution guidelines](./CONTRIBUTING.md)~~ [contribution guidelines](https://github.com/glutanimate/docs/blob/master/anki/add-ons/CONTRIBUTING.md) - it's not like they were linked from this repo.
- [ ] I've tested my changes against at least one of the following [Anki builds](https://apps.ankiweb.net/#download):
  - [ ] Latest standard Anki 2.1 binary build [required for Anki-compatible 2.1 add-ons]
  - [ ] Latest alternative Anki 2.1 binary build
  - [ ] Latest Anki 2.0 binary build [required for Anki 2.0-compatible add-ons]
- [ ] I've tested my changes on at least one of the following platforms:
  - [x] Linux, version: Debian 10 (buster), Python 3.7.3
  - [ ] Windows, version:
  - [ ] macOS, version: 
- [ ] My changes potentially affect non-desktop platforms, of which I've tested:
  - [ ] AnkiMobile, version:
  - [ ] AnkiDroid, version:
  - [ ] AnkiWeb

### CODE REVIEW

**Comment by glutanimate** [comment]
Hey zjosua,

Thanks for you work, and sorry for taking so long to respond.

This seems like a workable solution, but my main issue with it is that stashes persist in the git record, even if you do drop them (which the current approach doesn't). So I'm hesitant to merge this at the moment.

I think it might be best to steer away from git for handling uncommited changes. I recently stumbled on [gitignore_parser](https://github.com/mherrmann/gitignore_parser), so perhaps that might a good point to start from for our own implementation. We'd basically just have to modify it to also parse .gitattributes file (for the export-ignore lines), and we'd have canonical way to identify files that should be ignored in the build.

**Comment by zjosua** [comment]
The command `git stash create` does not actually save the stash but only creates a dangling commit, which we need for `git archive`. [git-stash manual](https://git-scm.com/docs/git-stash#Documentation/git-stash.txt-create)
The dangling commit can be removed by git's garbage collector: `git gc --prune=now`.
Note that git runs the garbage collector automatically after certain commands, but by default, only objects older than two weeks are pruned.

Here's the output from a test run:
```
zjosua@debian:~/sw_dev/mini-format-pack$ aab build -d local dev
Anki Add-on Builder v0.1.4

...

Done.
zjosua@debian:~/sw_dev/mini-format-pack$ git stash list
zjosua@debian:~/sw_dev/mini-format-pack$ git fsck
Checking object directories: 100% (256/256), done.
Checking objects: 100% (105/105), done.
dangling commit 5eddf863c2bf87edf64636db30e0358c01ede03a
zjosua@debian:~/sw_dev/mini-format-pack$ git gc --prune=now
Enumerating objects: 105, done.
Counting objects: 100% (105/105), done.
Delta compression using up to 2 threads
Compressing objects: 100% (53/53), done.
Writing objects: 100% (105/105), done.
Total 105 (delta 38), reused 105 (delta 38)
zjosua@debian:~/sw_dev/mini-format-pack$ git fsck
Checking object directories: 100% (256/256), done.
Checking objects: 100% (105/105), done.
```

**Comment by cofinley** [comment]
Is there a reason we can't just copy what's inside `src/` then compile the designer files to the build's `gui/forms` directory? I don't believe git files, licenses, changelogs, or original ui files need to be kept around for a final distribution (it also seems confusing that `dist/` contains `src/`). I think just having the `{module_name}/` and `{display_name}.py` inside `build/dist/` would suffice. Would that be problematic?

**Comment by cofinley** [comment]
I've made [a fork](https://github.com/glutanimate/anki-addon-builder/compare/master...ll-in-anki:master) with a few changes that reflect my last comment.

**Comment by glutanimate** [comment]
@zjosua Huh, interesting. That definitely makes it a lot more viable of a solution, but it still doesn't feel that clean. I'll have to give it some more thought, but I might just merge this for now to bridge the gap until we can find a more definitive solution.

@cofinley The issue is that src could contain all kinds of files you don't want to package. E.g. pycache, local config files, incomplete source files, etc. That's the advantage of having the package contents pre-specified through version tracking.

**Comment by glutanimate** [comment]
Merging this because it works well and is a good solution for the time being. Thanks again, @zjosua!

**Pull request merged**
